dist: bionic
language: java

git:
  depth: false

script:
  # Download the latest bob.jar
  - mkdir -p build/public || travis_terminate 1
  - mkdir -p build/bob || travis_terminate 1
  - curl -s 'http://d.defold.com/stable/info.json' | python3 -c "import sys, json; print('https://d.defold.com/archive/' + json.load(sys.stdin)['sha1'] + '/bob/bob.jar')" | wget --progress=dot:mega -i - -O build/bob/bob.jar || travis_terminate 1

  # Build the project
  - java -jar build/bob/bob.jar --email foo@bar.com --auth 12345 --texture-compression true --bundle-output build/bundle/js-web --build-report-html build/public/build_report_latest.html --platform js-web --archive --liveupdate yes --variant debug resolve build bundle || travis_terminate 1

  # Move LiveUpdate .zip file into the bundle dir as "resources.zip"
  - mv build/liveupdate_output/*.zip build/bundle/js-web/liveupdate_reszip_demo/resources.zip || travis_terminate 1

  # Move to the "latest" dir
  - mv build/bundle/js-web/liveupdate_reszip_demo build/public/latest || travis_terminate 1

  # Checkout alt version and build it
  - git checkout alt-version || travis_terminate 1
  - rm -rf build/bundle || travis_terminate 1
  - java -jar build/bob/bob.jar --email foo@bar.com --auth 12345 --texture-compression true --bundle-output build/bundle/js-web --build-report-html build/public/build_report_alt-version.html --platform js-web --archive --liveupdate yes --variant debug resolve build bundle || travis_terminate 1
  - mv build/liveupdate_output/*.zip build/bundle/js-web/liveupdate_reszip_demo/resources.zip || travis_terminate 1
  - mv build/bundle/js-web/liveupdate_reszip_demo build/public/alt-version || travis_terminate 1

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/public
  on:
    branch: main
